export const API_BASE_URL = 'http://localhost:5000/api';

export const daysOfWeek = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'];

export const translations = {
  en: {
    title: 'Attendance Management System',
    subtitle: 'Demo',
    export: 'Export',
    generateSchedule: 'Generate Schedule',
    processing: 'Processing...',
    dashboard: 'Dashboard',
    employees: 'Employees',
    roles: 'Roles',
    schedule: 'Schedule',
    dailyView: 'Daily View',
    attendance: 'Attendance',
    totalEmployees: 'Total Employees',
    totalRoles: 'Total Roles',
    shiftTypes: 'Shift Types',
    attendanceRecords: 'Attendance Records',
    systemOverview: 'System Overview',
    leaveRequests: 'Leave Requests',
    unavailability: 'Unavailability',
    employeeManagement: 'Employee Management',
    addEmployee: 'Add Employee',
    editEmployee: 'Edit Employee',
    newEmployee: 'New Employee',
    name: 'Name',
    role: 'Role',
    selectRole: 'Select a role',
    weeklyHours: 'Weekly Hours',
    dailyMaxHours: 'Daily Max Hours',
    skills: 'Skills (comma-separated)',
    save: 'Save',
    cancel: 'Cancel',
    close: 'Close',
    delete: 'Delete',
    edit: 'Edit',
    deleteConfirm: 'Delete this employee?',
    deleteRoleConfirm: 'Delete this role and all its shifts?',
    deleteShiftConfirm: 'Delete this shift?',
    fillRequired: 'Please fill required fields',
    enterRoleName: 'Please enter role name',
    roleManagement: 'Role Management',
    addRole: 'Add Role',
    editRole: 'Edit Role',
    newRole: 'New Role',
    roleName: 'Role Name',
    breakTime: 'Break Time (minutes)',
    requiredSkills: 'Required Skills (comma-separated)',
    weekendRequired: 'Weekend work required',
    shifts: 'Shifts',
    addShift: 'Add Shift',
    editShift: 'Edit Shift',
    newShift: 'New Shift',
    shiftName: 'Shift Name',
    priority: 'Priority (0-100)',
    daySchedule: 'Day Schedule',
    weeklySchedule: 'Weekly Schedule',
    noSchedule: 'No schedule generated yet',
    generateScheduleBtn: 'Click "Generate Schedule" to create one',
    dailyScheduleView: 'Daily Schedule',
    attendanceManagement: 'Attendance Management',
    status: 'Status',
    leave: 'Leave',
    unavailable: 'Unavailable',
    attendanceRecordsList: 'Attendance Records',
    recordBtn: 'Record',
    onTime: 'On time',
    slightlyLate: 'Slightly late',
    late: 'Late',
    selectEmployee: 'Select an employee',
    roleDoesNotMatch: 'Role does not match',
    selectDate: 'Select Date',
    timeSlots: 'Time Slots',
    noShiftsScheduled: 'No shifts scheduled for this day',
    availabilityStatus: 'Availability Status',
    arrivedAt: 'Arrived at',
    editSchedule: 'Edit Schedule',
    saveChanges: 'Save Changes',
    discardChanges: 'Discard Changes',
    editShiftTime: 'Edit Shift Time',
    startTime: 'Start Time',
    endTime: 'End Time',
    overtimeDetected: 'Overtime Detected',
    overtimeWarning: 'The following employees will work overtime:',
    weeklyMaxExceeded: 'Weekly max hours exceeded',
    continueWithOvertime: 'Continue and record overtime?',
    constraintViolation: 'Constraint Violation',
    consecutiveShiftsError: 'Cannot assign more than 5 consecutive shifts without a break',
    dragToReassign: 'Drag shifts to reassign',
    clickToEditTime: 'Click to edit time',
    selectShift: 'Select Shift',
    customTime: 'Custom Time',
    overtimeHours: 'Overtime Hours',
    totalOvertime: 'Total Overtime',
    noOvertime: 'No overtime recorded',
    deleteShiftConfirmSchedule: 'Delete this shift from schedule?',
    changeShiftType: 'Change Shift Type',
    dailyMaxWarning: 'Daily Max Hours Warning',
    dailyMaxExceeded: 'This shift exceeds the daily maximum hours',
    continueAnyway: 'Continue anyway?',
    dailyMax: 'Daily Max',
    shiftHours: 'Shift Hours',
    roleManagementTitle: 'Role Management',
    addRoleBtn: 'Add Role',
    breakLabel: 'Break',
    minLabel: 'min',
    weekendLabel: 'Weekend',
    requiredLabel: 'Required',
    notRequiredLabel: 'Not required',
    skillsLabel: 'Skills',
    shiftsLabel: 'Shifts',
    addShiftBtn: 'Add Shift',
    editShiftTitle: 'Edit Shift',
    newShiftTitle: 'New Shift',
    shiftNameLabel: 'Shift Name *',
    priorityLabel: 'Priority (0-100)',
    dayScheduleLabel: 'Day Schedule',
    workHours: 'Work Hours',
    totalShiftTime: 'Total Shift Time',
    workHoursSummary: 'Work Hours Summary',
    noWorkSchedule: 'No days enabled yet',
    morningPlaceholder: 'Morning',
    machineOperatorPlaceholder: 'Machine Operator',
    machineOpSkillPlaceholder: 'Machine operation, Quality assurance',
    daysLabel: 'Days',
    priortyLabel: 'Priority',
    dayPriorityLabel: 'Day Priority',
    earlyCheckInTitle: 'Early Check-In',
    earlyCheckInMsg: 'Check-in is more than 1 hour early',
    checkInTimeLabel: 'Check-in Time',
    shiftStartTimeLabel: 'Shift Start Time',
    minutesEarlyLabel: 'minutes early',
    goAheadBtn: 'Go Ahead',
    inTimeLabel: 'In Time',
    outTimeLabel: 'Out Time',
    recordAttendanceBtn: 'Record',
    addingShiftMsg: 'Adding this shift may result in overtime. You\'ll be prompted to confirm before saving.',
    scheduleGeneratedSuccess: '✅ Schedule generated and saved successfully!',
    scheduleUpdatedSuccess: '✅ Schedule updated successfully!',
    scheduleUpdateWithOvertimeSuccess: '✅ Schedule updated with overtime recorded!',
    scheduleConfirmedSuccess: '✅ Schedule confirmed and saved!',
    notificationSentSuccess: 'Notification sent successfully!',
    messageSentSuccess: 'Message sent successfully!',
    fillRequiredFields: 'Please fill required fields',
    enterInTime: 'Please enter in-time',
    breakRequiredError: 'Shifts longer than 4 hours require a break time to be configured for the role',
    employeeAlreadyHasShift: 'Employee already has a shift on this day',
    selectEmployeeAndMessage: 'Please select an employee and enter a message',
    fillAllFields: 'Please fill all fields',
    cannotMarkUnavailable: 'Cannot mark unavailable. Employee needs at least {days} days available.',
    scheduleTableNotFound: 'Schedule table not found',
    dailyScheduleNotFound: 'Daily schedule not found',
    roleScheduleNotFound: 'Role schedule not found',
    failedToDownloadSchedule: 'Failed to download schedule',
    failedToDownloadDailySchedule: 'Failed to download daily schedule',
    failedToDownloadAttendance: 'Failed to download attendance',
    failedToSaveSchedule: '❌ Failed to save schedule',
    failedToLoadForecast: 'Failed to load demand forecast: ',
    failedToConnectForecast: '❌ Failed to connect to forecast service.',
    failedToConnectBackend: '❌ Failed to connect to backend.',
    errorPrefix: '❌ Error: ',
    loginTitle: 'Attendance Management System ',
    userId: 'User ID',
    password: 'Password',
    loginBtn: 'Login',
    logout: 'Logout',
    invalidCredentials: 'Invalid credentials',
    mySchedule: 'My Schedule',
    confirmCheckIn: 'Confirm Check-In',
    confirmCheckOut: 'Confirm Check-Out',
    checkInTime: 'Check-In Time',
    checkOutTime: 'Check-Out Time',
    alreadyCheckedIn: 'Already checked in',
    alreadyCheckedOut: 'Already checked out',
    noShiftToday: 'No shift assigned for today',
    checkedIn: 'Checked In',
    checkedOut: 'Checked Out',
    missed: 'MISSED',
    notifications: 'Notifications',
    noNotifications: 'No notifications yet',
    sendNotification: 'Send Message',
    requestLeave: 'Request Leave',
    sendMessage: 'Send Message',
    messageToManager: 'Message to Manager',
    typeMessage: 'Type your message...',
    send: 'Send',
    leaveRequest: 'Leave Request',
    startDate: 'Start Date',
    endDate: 'End Date',
    reason: 'Reason',
    requestReason: 'Reason for leave...',
    submit: 'Submit',
    messages: 'Messages',
    noMessages: 'No messages',
    from: 'From',
    approve: 'Approve',
    reject: 'Reject',
    pending: 'Pending',
    approved: 'Approved',
    rejected: 'Rejected',
    messageSent: 'Message sent successfully!',
    leaveRequestSent: 'Leave request submitted!',
    leaveApproved: 'Leave request approved',
    leaveRejected: 'Leave request rejected',
    recordOvertimeBtn: 'Record Overtime & Save',
    noteLabel: 'Note',
    plannedHours: 'Planned Hours',
    inTime: 'In Time',
    outTime: 'Out Time',
    japanLocalTime: 'Japan Local Time',
    Monday: 'Monday',
    Tuesday: 'Tuesday',
    Wednesday: 'Wednesday',
    Thursday: 'Thursday',
    Friday: 'Friday',
    Saturday: 'Saturday',
    Sunday: 'Sunday',
    confirmSchedule: 'Confirm & Save',
    downloadPDF: 'Download PDF',
    printSchedule: 'Print',
    demandForecast: 'Demand Forecast',
    loadForecast: 'Load Forecast',
    forecastingLoadingDemand: 'Forecasting demand...',
    peakDay: 'Peak Day',
    lowestDemand: 'Lowest Demand',
    historicalRange: 'Historical Range',
    trend: 'Trend',
    predictedEmployees: 'Predicted Employees',
    confidence: 'Confidence',
    insights: 'Key Insights',
    recommendations: 'Recommendations',
    roleBasedForecast: 'Role-Based Forecast',
    averageDemand: 'Average Demand',
    peakDemand: 'Peak Demand',
    variability: 'Variability',
    absenceRate: 'Absence Rate',
    overtimeShifts: 'Avg Overtime Shifts',
    weeklyBreakdown: 'Weekly Breakdown',
    range: 'Range',
    historicalWeeks: 'Historical Weeks',
    scheduleConfidence: 'Schedule Confidence',
    dateAndDay: 'Date & Day',
    shiftTimings: 'Shift Timings',
    hours: 'Hours',
    veryLate: 'Very Late',
    break: 'Break',
    minutes: 'minutes',
    downloadWeeklyAttendance: 'Download Weekly Attendance',
    downloadMonthlyAttendance: 'Download Monthly Attendance'
  },
  ja: {
    title: '勤怠管理システム',
    subtitle: 'デモ',
    export: 'エクスポート',
    generateSchedule: 'スケジュール生成',
    processing: '処理中...',
    dashboard: 'ダッシュボード',
    employees: '従業員',
    roles: 'ロール',
    schedule: 'スケジュール',
    dailyView: '日別表示',
    attendance: '出勤',
    totalEmployees: '総従業員数',
    totalRoles: '総ロール数',
    shiftTypes: 'シフトタイプ',
    attendanceRecords: '出勤記録',
    systemOverview: 'システム概要',
    leaveRequests: '休暇申請',
    unavailability: '利用不可',
    employeeManagement: '従業員管理',
    addEmployee: '従業員を追加',
    editEmployee: '従業員を編集',
    newEmployee: '新しい従業員',
    name: '名前',
    role: 'ロール',
    selectRole: 'ロールを選択してください',
    weeklyHours: '週間時間',
    dailyMaxHours: '1日の最大時間',
    skills: 'スキル（カンマ区切り）',
    save: '保存',
    cancel: 'キャンセル',
    close: '閉じる',
    delete: '削除',
    edit: '編集',
    deleteConfirm: 'この従業員を削除しますか？',
    deleteRoleConfirm: 'このロールとすべてのシフトを削除しますか？',
    deleteShiftConfirm: 'このシフトを削除しますか？',
    fillRequired: '必須フィールドに入力してください',
    enterRoleName: 'ロール名を入力してください',
    roleManagement: 'ロール管理',
    addRole: 'ロールを追加',
    editRole: 'ロールを編集',
    newRole: '新しいロール',
    roleName: 'ロール名',
    breakTime: '休憩時間（分）',
    requiredSkills: '必要なスキル（カンマ区切り）',
    weekendRequired: '週末の勤務が必須',
    shifts: 'シフト',
    addShift: 'シフトを追加',
    editShift: 'シフトを編集',
    newShift: '新しいシフト',
    shiftName: 'シフト名',
    priority: '優先度（0-100）',
    daySchedule: '日程',
    weeklySchedule: '週間スケジュール',
    noSchedule: 'スケジュールはまだ生成されていません',
    generateScheduleBtn: '"スケジュール生成"をクリックして作成します',
    dailyScheduleView: '日別スケジュール',
    attendanceManagement: '出勤管理',
    status: 'ステータス',
    leave: '休暇',
    unavailable: '利用不可',
    attendanceRecordsList: '出勤記録',
    recordBtn: '記録',
    onTime: '定時',
    slightlyLate: 'やや遅刻',
    late: '遅刻',
    selectEmployee: '従業員を選択',
    roleDoesNotMatch: 'ロールが一致しません',
    selectDate: '日付を選択',
    timeSlots: 'タイムスロット',
    noShiftsScheduled: 'この日はシフトがスケジュール済みです',
    availabilityStatus: '利用可能ステータス',
    arrivedAt: '到着時間',
    editSchedule: 'スケジュール編集',
    saveChanges: '変更を保存',
    discardChanges: '変更を破棄',
    editShiftTime: 'シフト時間を編集',
    startTime: '開始時間',
    endTime: '終了時間',
    overtimeDetected: '残業検出',
    overtimeWarning: '以下の従業員が残業になります：',
    weeklyMaxExceeded: '週間最大時間を超過',
    continueWithOvertime: '残業を記録して続行しますか？',
    constraintViolation: '制約違反',
    consecutiveShiftsError: '5日以上連続のシフトはできません（1日以上の休暇が必要です）',
    dragToReassign: 'ドラッグして再割り当て',
    clickToEditTime: 'クリックして時間を編集',
    selectShift: 'シフトを選択',
    customTime: 'カスタム時間',
    overtimeHours: '残業時間',
    totalOvertime: '総残業時間',
    noOvertime: '残業記録なし',
    deleteShiftConfirmSchedule: 'このシフトをスケジュールから削除しますか？',
    changeShiftType: 'シフトタイプを変更',
    dailyMaxWarning: '日次最大時間警告',
    dailyMaxExceeded: 'このシフトは1日の最大時間を超えています',
    continueAnyway: 'それでも続行しますか？',
    dailyMax: '日次最大',
    shiftHours: 'シフト時間',
    editRoleTitle: 'ロールを編集',
    newRoleTitle: '新しいロール',
    roleManagementTitle: 'ロール管理',
    addRoleBtn: 'ロールを追加',
    breakLabel: '休憩',
    minLabel: '分',
    weekendLabel: '週末',
    requiredLabel: '必須',
    notRequiredLabel: '必須なし',
    skillsLabel: 'スキル',
    shiftsLabel: 'シフト',
    addShiftBtn: 'シフトを追加',
    editShiftTitle: 'シフトを編集',
    newShiftTitle: '新しいシフト',
    shiftNameLabel: 'シフト名 *',
    priorityLabel: '優先度 (0-100)',
    dayScheduleLabel: '日程',
    workHours: '勤務時間',
    totalShiftTime: 'シフト総時間',
    workHoursSummary: '勤務時間サマリー',
    noWorkSchedule: 'まだ有効な日がありません',
    morningPlaceholder: '朝',
    machineOperatorPlaceholder: 'マシンオペレーター',
    machineOpSkillPlaceholder: '機械操作、品質保証',
    daysLabel: '日数',
    priortyLabel: '優先度',
    dayPriorityLabel: '日の優先度',
    earlyCheckInTitle: '早期チェックイン',
    earlyCheckInMsg: 'チェックインが1時間以上早い',
    checkInTimeLabel: 'チェックイン時間',
    shiftStartTimeLabel: 'シフト開始時間',
    minutesEarlyLabel: '分早い',
    goAheadBtn: '進める',
    inTimeLabel: '入退勤時間',
    outTimeLabel: '退勤時間',
    recordAttendanceBtn: '記録',
    addingShiftMsg: 'このシフトを追加すると、残業が発生する可能性があります。保存する前に確認を求めます。',
    scheduleGeneratedSuccess: '✅ スケジュールが正常に生成・保存されました！',
    scheduleUpdatedSuccess: '✅ スケジュールが正常に更新されました！',
    scheduleUpdateWithOvertimeSuccess: '✅ スケジュールが残業記録で更新されました！',
    scheduleConfirmedSuccess: '✅ スケジュールが確認・保存されました！',
    notificationSentSuccess: '通知が正常に送信されました！',
    messageSentSuccess: 'メッセージが正常に送信されました！',
    fillRequiredFields: '必須フィールドに入力してください',
    enterInTime: '入退勤時間を入力してください',
    breakRequiredError: '4時間を超えるシフトにはロールの休憩時間設定が必要です',
    employeeAlreadyHasShift: 'この従業員はこの日にすでにシフトがあります',
    selectEmployeeAndMessage: '従業員を選択してメッセージを入力してください',
    fillAllFields: 'すべてのフィールドに入力してください',
    cannotMarkUnavailable: '利用不可にできません。従業員は最低でも{days}日利用可能である必要があります。',
    scheduleTableNotFound: 'スケジュール表が見つかりません',
    dailyScheduleNotFound: '日別スケジュールが見つかりません',
    roleScheduleNotFound: 'ロールスケジュールが見つかりません',
    failedToDownloadSchedule: 'スケジュールのダウンロードに失敗しました',
    failedToDownloadDailySchedule: '日別スケジュールのダウンロードに失敗しました',
    failedToDownloadAttendance: '出勤記録のダウンロードに失敗しました',
    failedToSaveSchedule: '❌ スケジュール保存に失敗しました',
    failedToLoadForecast: '需要予測の読み込みに失敗しました: ',
    failedToConnectForecast: '❌ 予測サービスへの接続に失敗しました。',
    failedToConnectBackend: '❌ バックエンドへの接続に失敗しました。',
    errorPrefix: '❌ エラー: ',
    loginTitle: '勤怠管理システム',
    userId: 'ユーザーID',
    password: 'パスワード',
    loginBtn: 'ログイン',
    logout: 'ログアウト',
    invalidCredentials: '無効な認証情報',
    mySchedule: '私のスケジュール',
    confirmCheckIn: 'チェックインを確認',
    confirmCheckOut: 'チェックアウトを確認',
    checkInTime: 'チェックイン時間',
    checkOutTime: 'チェックアウト時間',
    alreadyCheckedIn: 'すでにチェックイン済み',
    alreadyCheckedOut: 'すでにチェックアウト済み',
    noShiftToday: '今日はシフトが割り当てられていません',
    checkedIn: 'チェックイン済み',
    checkedOut: 'チェックアウト済み',
    missed: '欠席',
    notifications: '通知',
    noNotifications: '通知はまだありません',
    sendNotification: 'メッセージを送信',
    requestLeave: '休暇申請',
    sendMessage: 'メッセージを送信',
    messageToManager: 'マネージャーへのメッセージ',
    typeMessage: 'メッセージを入力...',
    send: '送信',
    leaveRequest: '休暇申請',
    startDate: '開始日',
    endDate: '終了日',
    reason: '理由',
    requestReason: '休暇の理由...',
    submit: '送信',
    messages: 'メッセージ',
    noMessages: 'メッセージなし',
    from: '送信者',
    approve: '承認',
    reject: '却下',
    pending: '保留中',
    approved: '承認済み',
    rejected: '却下',
    messageSent: 'メッセージが送信されました！',
    leaveRequestSent: '休暇申請が送信されました！',
    leaveApproved: '休暇申請が承認されました',
    leaveRejected: '休暇申請が却下されました',
    recordOvertimeBtn: '残業を記録して保存',
    noteLabel: '注記',
    plannedHours: '計画時間',
    inTime: 'イン タイム',
    outTime: 'アウト タイム',
    japanLocalTime: '日本現地時間',
    Monday: '月曜日',
    Tuesday: '火曜日',
    Wednesday: '水曜日',
    Thursday: '木曜日',
    Friday: '金曜日',
    Saturday: '土曜日',
    Sunday: '日曜日',
    confirmSchedule: '確認して保存',
    downloadPDF: 'PDFダウンロード',
    printSchedule: '印刷',
    demandForecast: '需要予測',
    loadForecast: '予測を読み込み',
    forecastingLoadingDemand: '需要を予測中...',
    peakDay: 'ピークの日',
    lowestDemand: '最低需要',
    historicalRange: '過去の範囲',
    trend: 'トレンド',
    predictedEmployees: '予測従業員数',
    confidence: '信頼度',
    insights: '主要な洞察',
    recommendations: '推奨事項',
    roleBasedForecast: 'ロール別予測',
    averageDemand: '平均需要',
    peakDemand: 'ピーク需要',
    variability: '変動性',
    absenceRate: '欠席率',
    overtimeShifts: '平均残業シフト',
    weeklyBreakdown: '週別の分析',
    range: '範囲',
    historicalWeeks: '過去データ週数',
    scheduleConfidence: 'スケジュール信頼度',
    dateAndDay: '日付と曜日',
    shiftTimings: 'シフト時間',
    hours: '時間',
    veryLate: '大幅遅刻',
    break: '休憩',
    minutes: '分',
    downloadWeeklyAttendance: '週間出勤記録をダウンロード',
    downloadMonthlyAttendance: '月間出勤記録をダウンロード'
  }
};

export function getWeekDates() {
  const today = new Date();
  const first = today.getDate() - today.getDay() + 1;
  const week = [];
  for (let i = 0; i < 7; i++) {
    const day = new Date(today.setDate(first + i));
    week.push(day.toISOString().split('T')[0]);
  }
  return week;
}
